### ISSUE TITLE
Replay mod breaks in current version (r97)

### ISSUE THREAD

**Issue by ResidentNintendoNerd** [ADOFAI-gg/ADOFAI-Replay#1]
Currently, whenever the mod is enabled, all screen transitions stop working and will show a black screen until the mod is disabled from the menu (even during the game).

https://user-images.githubusercontent.com/72361126/192914520-1516bd66-a6e0-456b-87e1-8e00ee16f73e.mp4

**Comment by NoBrain0917** [comment]
fixed in v1.2.0, you can download it here
https://github.com/NoBrain0917/ADOFAI-Replay/releases/tag/v1.2.0
